### ISSUE TITLE
Login error with cross-realm characters

### ISSUE THREAD

**Issue by mrozekma** [mrozekma/KeystoneQuery#18]
https://mods.curse.com/addons/wow/keystone-query?comment=19

> Also, when logging in from a cross-realm character, I seem to be getting a "No player named Character-Server is currently playing" on login.

**Comment by Cy4n1d3** [comment]
This happens a lot to me.
Mostly (or even always) if a user with `KeystoneQuery` logs onto a character on a different realm and then logs off again. Very noisy if someone is logging through 20 characters and one is greeted by 5 to 10 error messages - per character.

**Comment by Cy4n1d3** [comment]
I confirmed the behavior, couldn't see anything obvious in the error log though.
To reproduce: have someone using your addon log onto a character on a different realm than your own (was a connected realm in my testcase), wait a second and log off again.
You will receive 5 messages telling you, that no player with that name is currently playing.

**Comment by mrozekma** [comment]
I think I figured out the problem; it's hard to be sure. 2.10 is in beta right now, you can try installing that (or wait for the actual release in a couple days). Let me know if you're still seeing it

**Comment by Cy4n1d3** [comment]
I'll report back if I notice any further problems but so far it's looking great.
Both #17 and #18 seem to be fixed for me, thx!
