### ISSUE TITLE
Keystone shows as depleted but is not

### ISSUE THREAD

**Issue by mackay2k4** [mrozekma/KeystoneQuery#20]
I have athe problem, that the keystones are shown as depleted but are not. Also not all affixes are showing. 
I am on version 2.11 and WoW on 7.2.5

This is my key from the bag:
http://fs5.directupload.net/images/170617/387gpo6j.jpg

by posting /key? it shows:
http://fs5.directupload.net/images/170617/uskk635b.jpg

by posting `:key:` it shows:
[Schlüsselstein: Der Seelenschlund] -- Der Seelenschlund +9 (bebend) (depleted)

Titanpanel shows:
http://fs5.directupload.net/images/170617/rjs5ks4n.jpg

Can anyone help?

**Comment by mackay2k4** [comment]
I found where the problem in the addon is. In KeystoneQuery.lua
Line 135: 	**tinsert(affixIDs, tonumber(parts[_5_ + i]))** 
needs to be **tinsert(affixIDs, tonumber(parts[_4_ + i]))**

Line 137: **local lootEligible = (tonumber(parts[5]) == 1)**
needs to be: **local lootEligible = 1**

Line 185 needs to be changes to below: (removed  `:%d` and `keystone.lootEligible and '1' or '0' ` )

`link = format("|TInterface\\Icons\\Achievement_PVP_A_%02d:16|t |cff%s|Hkeystone:%d:%d:%d:%d:%d|h[%s +%d]|r", min(keystone.keystoneLevel, 15), linkColor, keystone.dungeonID, keystone.keystoneLevel, keystone.affixIDs[1] or 0, keystone.affixIDs[2] or 0, keystone.affixIDs[3] or 0, dungeonName, keystone.keystoneLevel)
`

It seems that the changes in 7.2.5 removed the "Depleted" part in the links. 
Its kind of a dirty fix but should work until some one with better knowledge of this addon can remove the depleted part complete.

**Comment by mrozekma** [comment]
Fixed (I think) in 0b1825896b100782f5a64c3760592fa4cc12deac, 0d7cdb1c1a85af8da103cbcf904e668eba22d670
